# Sidebar navigation

- label: หน้าแรก
  link: /
- label: ทำไมยังเล่น MD
  link: /why-minidisc
- label: คำแนะนำเบื้องต้นสำหรับผู้เริ่มต้นใช้งาน MD
  link: /getting-started-th
- label: รวมคำถามที่พบบ่อย (MD FAQ)
  link: /faq

- label: เรื่องเล่า MiniDisc
  link: /minidisc-story
- label: เว็บไซต์เพื่อนบ้าน
  link: /friends-websites
- label: Privacy Policy
  link: /privacy-policy

- label: Net MD
  items:
    - label: Web MiniDisc User Guide
      link: /netmd/web-minidisc-user-guide
    - label: คู่มือใช้งาน Web MiniDisc ภาษาไทย
      link: /netmd/web-minidisc-user-guide-th
    - label: Net MD infographic
      link: /netmd/netmd-infographic

    - label: คู่มือติดตั้งและใช้งานโปรแกรม SonicStage
      link: /netmd/sonic-stage-manual
    - label: คู่มือติดตั้งและใช้งานโปรแกรม MD Simple Burner
      link: /netmd/md-simple-burner-manual

    - label: เครื่องเล่นที่รองรับ Net MD
      link: /netmd/netmd-players
    - label: Sony Net MD decks
      link: /netmd/sony-netmd-decks

    - label: รู้จัก MD recording mode
      link: /netmd/md-recording-mode
    - label: ทดสอบเวลาที่ในการเขียนเพลง MP3 ลงแผ่น MD
      link: /netmd/writing-disc-time-usage-test

    - label: Advantages of Net MD
      link: /netmd/advantages-of-netmd
    - label: ข้อดีของ Net MD
      link: /netmd/advantages-of-netmd-th
    - label: ทำไมในอดีต Net MD จึงเสียงไม่ดี
      link: /netmd/why-did-netmd-not-produce-good-sound-quality-in-the-past

    - label: รีวิวคุณภาพเสียงจากแผ่นที่อัดด้วย Net MD
      link: /netmd/netmd-sound-quality-review
    - label: Copy audio CD to MD
      link: /netmd/copy-audio-cd-to-md
    - label: การอัด 1:1 (digital input) และ Net MD (Web MiniDisc) ให้ผลลัพธ์ต่างกันในแบบที่เราฟังแล้วแยกออกหรือไม่
      link: /netmd/do-one-to-one-and-netmd-recording-produce-different-output

    - label: ข้อแตกต่างระหว่างการอัดด้วยวิธี 1:1 (digital input) และ Net MD (Web MiniDisc)
      link: /netmd/differences-between-one-to-one-and-netmd-recording

- label: Useful resources
  items:
    - label: Yahoo Auction Japan calculator
      link: /useful-resources/yahoo-auction-japan-calculator

    - label: Yellow portable MD players/recorders collection
      link: /useful-resources/yellow-portable-md-players-recorders-collection

    - label: MD players'/recorders' model names
      link: /useful-resources/md-players-recorders-model-names

    - label: รีโมทรุ่นต่างๆ ของ Sony MD
      link: /useful-resources/sony-md-remotes
    - label: Sony MD power adapter
      link: /useful-resources/sony-md-power-adapter

    - label: MD head-lens cleaner
      link: /useful-resources/md-head-lens-cleaner

    - label: A cheap music streamer with an MD deck
      link: /useful-resources/a-cheap-music-streamer-with-an-md-deck

    - label: รวม Wiki ข้อมูลของเครื่องเล่นแบบต่างๆ
      link: /useful-resources/audio-player-wiki
    - label: Interesting players with VU meters
      link: /useful-resources/interesting-players-with-vu-meters
    - label: Reel to reel cassette tape
      link: /useful-resources/reel-to-reel-cassette-tape

    - label: MD player parts and accessories
      link: /useful-resources/md-player-parts-and-accessories
    - label: Adjustable metal headband on-ear headphones (ก้านเหล็ก)
      link: /useful-resources/adjustable-metal-headband-on-ear-headphones

    - label: MP3 to cassette tape adapter
      link: /useful-resources/mp3-to-cassette-tape-adapter
    - label: Recommended CD Walkman players
      link: /useful-resources/recommended-cd-walkman-players
    - label: 1:1 recoding with music sync instructions
      link: /useful-resources/1-to-1-music-sync-instructions

    - label: Portable digital audio players (DAPs) with digital output
      link: /useful-resources/portable-daps-with-digital-output


