name: Build and deploy Gatsby to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 14.x # Set Node.js version to use.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest source code from ${{ github.sha }} commit
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Use Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2 # https://github.com/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build Gatsby site to a public folder
        # Yarn's already installed on a virtual environment
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#package-management
        run: |
          yarn install
          yarn run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1 # https://github.com/actions/upload-pages-artifact/releases
        with:
          path: ./only-minidisc/public


  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 # https://github.com/actions/deploy-pages/releases
